In [1]:
import pandas as pd

# EPL Statistics

In [2]:
#EPL stats
shooting_eng=pd.read_csv('/Users/msyzdykova/Desktop/dataset DS project/eng/shooting.csv')
passing_eng=pd.read_csv('/Users/msyzdykova/Desktop/dataset DS project/eng/passing.csv')
gca_eng=pd.read_csv('/Users/msyzdykova/Desktop/dataset DS project/eng/gca.csv')
defense_eng=pd.read_csv('/Users/msyzdykova/Desktop/dataset DS project/eng/defense.csv')
misc_eng=pd.read_csv('/Users/msyzdykova/Desktop/dataset DS project/eng/misc.csv')
possession_eng=pd.read_csv('/Users/msyzdykova/Desktop/dataset DS project/eng/possession.csv')

In [3]:
for i in [shooting_eng, passing_eng, gca_eng, defense_eng, possession_eng, misc_eng]:
    print(i.columns)

Index(['Unnamed: 0', 'Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born',
       '90s', 'Standard_Gls', 'Standard_Sh', 'Standard_SoT', 'Standard_SoT%',
       'Standard_Sh/90', 'Standard_SoT/90', 'Standard_G/Sh', 'Standard_G/SoT',
       'Standard_Dist', 'Standard_FK', 'Standard_PK', 'Standard_PKatt',
       'Expected_xG', 'Expected_npxG', 'Expected_npxG/Sh', 'Expected_G-xG',
       'Expected_np:G-xG', 'Matches'],
      dtype='object')
Index(['Unnamed: 0', 'Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born',
       '90s', 'Total_Cmp', 'Total_Att', 'Total_Cmp%', 'Total_TotDist',
       'Total_PrgDist', 'Short_Cmp', 'Short_Att', 'Short_Cmp%', 'Medium_Cmp',
       'Medium_Att', 'Medium_Cmp%', 'Long_Cmp', 'Long_Att', 'Long_Cmp%', 'Ast',
       'xAG', 'Expected_xA', 'Expected_A-xAG', 'KP', '1/3', 'PPA', 'CrsPA',
       'PrgP', 'Matches'],
      dtype='object')
Index(['Unnamed: 0', 'Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born',
       '90s', 'SCA_SCA', 'SCA_SCA90', 'SCA Types_PassLive',
       'SCA Types_PassDead', 'SCA Types_TO', 'SCA Types_Sh', 'SCA Types_Fld',
       'SCA Types_Def', 'GCA_GCA', 'GCA_GCA90', 'GCA Types_PassLive',
       'GCA Types_PassDead', 'GCA Types_TO', 'GCA Types_Sh', 'GCA Types_Fld',
       'GCA Types_Def', 'Matches'],
      dtype='object')
Index(['Unnamed: 0', 'Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born',
       '90s', 'Tackles_Tkl', 'Tackles_TklW', 'Tackles_Def 3rd',
       'Tackles_Mid 3rd', 'Tackles_Att 3rd', 'Challenges_Tkl',
       'Challenges_Att', 'Challenges_Tkl%', 'Challenges_Lost', 'Blocks_Blocks',
       'Blocks_Sh', 'Blocks_Pass', 'Int', 'Tkl+Int', 'Clr', 'Err', 'Matches'],
      dtype='object')
Index(['Unnamed: 0', 'Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born',
       '90s', 'Touches_Touches', 'Touches_Def Pen', 'Touches_Def 3rd',
       'Touches_Mid 3rd', 'Touches_Att 3rd', 'Touches_Att Pen', 'Touches_Live',
       'Take-Ons_Att', 'Take-Ons_Succ', 'Take-Ons_Succ%', 'Take-Ons_Tkld',
       'Take-Ons_Tkld%', 'Carries_Carries', 'Carries_TotDist',
       'Carries_PrgDist', 'Carries_PrgC', 'Carries_1/3', 'Carries_CPA',
       'Carries_Mis', 'Carries_Dis', 'Receiving_Rec', 'Receiving_PrgR',
       'Matches'],
      dtype='object')
Index(['Unnamed: 0', 'Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born',
       '90s', 'Performance_CrdY', 'Performance_CrdR', 'Performance_2CrdY',
       'Performance_Fls', 'Performance_Fld', 'Performance_Off',
       'Performance_Crs', 'Performance_Int', 'Performance_TklW',
       'Performance_PKwon', 'Performance_PKcon', 'Performance_OG',
       'Performance_Recov', 'Aerial Duels_Won', 'Aerial Duels_Lost',
       'Aerial Duels_Won%', 'Matches'],
      dtype='object')

In [4]:
#Dropping unnecessary columns
for i in [shooting_eng, passing_eng, gca_eng, defense_eng, possession_eng, misc_eng]:
    i.drop(columns=['Unnamed: 0', 'Rk', 'Born', 'Matches'], inplace=True)

In [5]:
#Dealing with duplicates
#There are duplicates in our dataset from: the way data is organized on the website:
#it contains dividers between groups of players, so we need to drop all of them
dfs = [shooting_eng, passing_eng, gca_eng, defense_eng, possession_eng, misc_eng]

for i, df in enumerate(dfs):
    df = df[df['Player'] != 'Player']

    dfs[i] = df
    
shooting_eng, passing_eng, gca_eng, defense_eng, possession_eng, misc_eng = dfs

In [6]:
for i in [shooting_eng, passing_eng, gca_eng, defense_eng, possession_eng, misc_eng]:
    print(i.dtypes)

Player              object
Nation              object
Pos                 object
Squad               object
Age                 object
90s                 object
Standard_Gls        object
Standard_Sh         object
Standard_SoT        object
Standard_SoT%       object
Standard_Sh/90      object
Standard_SoT/90     object
Standard_G/Sh       object
Standard_G/SoT      object
Standard_Dist       object
Standard_FK         object
Standard_PK         object
Standard_PKatt      object
Expected_xG         object
Expected_npxG       object
Expected_npxG/Sh    object
Expected_G-xG       object
Expected_np:G-xG    object
dtype: object
Player            object
Nation            object
Pos               object
Squad             object
Age               object
90s               object
Total_Cmp         object
Total_Att         object
Total_Cmp%        object
Total_TotDist     object
Total_PrgDist     object
Short_Cmp         object
Short_Att         object
Short_Cmp%        object
Medium_Cmp        object
Medium_Att        object
Medium_Cmp%       object
Long_Cmp          object
Long_Att          object
Long_Cmp%         object
Ast               object
xAG               object
Expected_xA       object
Expected_A-xAG    object
KP                object
1/3               object
PPA               object
CrsPA             object
PrgP              object
dtype: object
Player                object
Nation                object
Pos                   object
Squad                 object
Age                   object
90s                   object
SCA_SCA               object
SCA_SCA90             object
SCA Types_PassLive    object
SCA Types_PassDead    object
SCA Types_TO          object
SCA Types_Sh          object
SCA Types_Fld         object
SCA Types_Def         object
GCA_GCA               object
GCA_GCA90             object
GCA Types_PassLive    object
GCA Types_PassDead    object
GCA Types_TO          object
GCA Types_Sh          object
GCA Types_Fld         object
GCA Types_Def         object
dtype: object
Player             object
Nation             object
Pos                object
Squad              object
Age                object
90s                object
Tackles_Tkl        object
Tackles_TklW       object
Tackles_Def 3rd    object
Tackles_Mid 3rd    object
Tackles_Att 3rd    object
Challenges_Tkl     object
Challenges_Att     object
Challenges_Tkl%    object
Challenges_Lost    object
Blocks_Blocks      object
Blocks_Sh          object
Blocks_Pass        object
Int                object
Tkl+Int            object
Clr                object
Err                object
dtype: object
Player             object
Nation             object
Pos                object
Squad              object
Age                object
90s                object
Touches_Touches    object
Touches_Def Pen    object
Touches_Def 3rd    object
Touches_Mid 3rd    object
Touches_Att 3rd    object
Touches_Att Pen    object
Touches_Live       object
Take-Ons_Att       object
Take-Ons_Succ      object
Take-Ons_Succ%     object
Take-Ons_Tkld      object
Take-Ons_Tkld%     object
Carries_Carries    object
Carries_TotDist    object
Carries_PrgDist    object
Carries_PrgC       object
Carries_1/3        object
Carries_CPA        object
Carries_Mis        object
Carries_Dis        object
Receiving_Rec      object
Receiving_PrgR     object
dtype: object
Player               object
Nation               object
Pos                  object
Squad                object
Age                  object
90s                  object
Performance_CrdY     object
Performance_CrdR     object
Performance_2CrdY    object
Performance_Fls      object
Performance_Fld      object
Performance_Off      object
Performance_Crs      object
Performance_Int      object
Performance_TklW     object
Performance_PKwon    object
Performance_PKcon    object
Performance_OG       object
Performance_Recov    object
Aerial Duels_Won     object
Aerial Duels_Lost    object
Aerial Duels_Won%    object
dtype: object

In [7]:
#Reformatting numerical columns from string to float
dfs = [shooting_eng, passing_eng, gca_eng, defense_eng, possession_eng, misc_eng]

for i, df in enumerate(dfs):

    numeric_cols = df.columns[4:]
    
    for col in numeric_cols:
        if df[col].dtype == 'object':
            if col.endswith('%'):
                df[col] = df[col].str.replace('%', '').astype(float) / 100
            else:
                df[col] = pd.to_numeric(df[col], errors='coerce')

    dfs[i] = df

shooting_eng, passing_eng, gca_eng, defense_eng, possession_eng, misc_eng = dfs

In [8]:
#Random checks
print(passing_eng['90s'].max())
print(shooting_eng['Standard_SoT%'])

38.0
0      0.000
1        NaN
2        NaN
3      0.357
4      0.452
       ...
598    0.370
599    0.333
600    0.176
601    0.438
602    0.280
Name: Standard_SoT%, Length: 580, dtype: float64

In [9]:
#Check for NaN values
for i in [shooting_eng, passing_eng, gca_eng, defense_eng, possession_eng, misc_eng]:
    print(i.isna().sum())

Player                0
Nation                0
Pos                   0
Squad                 0
Age                   0
90s                   0
Standard_Gls          0
Standard_Sh           0
Standard_SoT          0
Standard_SoT%       115
Standard_Sh/90        0
Standard_SoT/90       0
Standard_G/Sh       115
Standard_G/SoT      178
Standard_Dist       115
Standard_FK           0
Standard_PK           0
Standard_PKatt        0
Expected_xG           0
Expected_npxG         0
Expected_npxG/Sh    115
Expected_G-xG         0
Expected_np:G-xG      0
dtype: int64
Player             0
Nation             0
Pos                0
Squad              0
Age                0
90s                0
Total_Cmp          0
Total_Att          0
Total_Cmp%        10
Total_TotDist      0
Total_PrgDist      0
Short_Cmp          0
Short_Att          0
Short_Cmp%        19
Medium_Cmp         0
Medium_Att         0
Medium_Cmp%       24
Long_Cmp           0
Long_Att           0
Long_Cmp%         57
Ast                0
xAG                0
Expected_xA        0
Expected_A-xAG     0
KP                 0
1/3                0
PPA                0
CrsPA              0
PrgP               0
dtype: int64
Player                0
Nation                0
Pos                   0
Squad                 0
Age                   0
90s                   0
SCA_SCA               0
SCA_SCA90             0
SCA Types_PassLive    0
SCA Types_PassDead    0
SCA Types_TO          0
SCA Types_Sh          0
SCA Types_Fld         0
SCA Types_Def         0
GCA_GCA               0
GCA_GCA90             0
GCA Types_PassLive    0
GCA Types_PassDead    0
GCA Types_TO          0
GCA Types_Sh          0
GCA Types_Fld         0
GCA Types_Def         0
dtype: int64
Player              0
Nation              0
Pos                 0
Squad               0
Age                 0
90s                 0
Tackles_Tkl         0
Tackles_TklW        0
Tackles_Def 3rd     0
Tackles_Mid 3rd     0
Tackles_Att 3rd     0
Challenges_Tkl      0
Challenges_Att      0
Challenges_Tkl%    74
Challenges_Lost     0
Blocks_Blocks       0
Blocks_Sh           0
Blocks_Pass         0
Int                 0
Tkl+Int             0
Clr                 0
Err                 0
dtype: int64
Player              0
Nation              0
Pos                 0
Squad               0
Age                 0
90s                 0
Touches_Touches     0
Touches_Def Pen     0
Touches_Def 3rd     0
Touches_Mid 3rd     0
Touches_Att 3rd     0
Touches_Att Pen     0
Touches_Live        0
Take-Ons_Att        0
Take-Ons_Succ       0
Take-Ons_Succ%     92
Take-Ons_Tkld       0
Take-Ons_Tkld%     92
Carries_Carries     0
Carries_TotDist     0
Carries_PrgDist     0
Carries_PrgC        0
Carries_1/3         0
Carries_CPA         0
Carries_Mis         0
Carries_Dis         0
Receiving_Rec       0
Receiving_PrgR      0
dtype: int64
Player                0
Nation                0
Pos                   0
Squad                 0
Age                   0
90s                   0
Performance_CrdY      0
Performance_CrdR      0
Performance_2CrdY     0
Performance_Fls       0
Performance_Fld       0
Performance_Off       0
Performance_Crs       0
Performance_Int       0
Performance_TklW      0
Performance_PKwon     0
Performance_PKcon     0
Performance_OG        0
Performance_Recov     0
Aerial Duels_Won      0
Aerial Duels_Lost     0
Aerial Duels_Won%    50
dtype: int64

In [10]:
#Check NaN values in shooting stats

#Check distance in shooting stats
#Since the players that have NaN values for Standard_G/SoT, in general, have no other stats (they're all 0), we'll set this column to 0 too
print(shooting_eng[shooting_eng['Standard_Dist'].isna()].iloc[:,6:].sum(axis=1).sum())

#Check Standard_SoT%, Standard_G/Sh, Standard_G/SoT
#These columns have NaN values because the values that they are divided by 0, which in undefined -> so we feel justified to set these values 0
print(shooting_eng[shooting_eng['Standard_SoT%'].isna()]['Standard_SoT'].sum())
print(shooting_eng[shooting_eng['Standard_G/Sh'].isna()]['Standard_Sh'].sum())
print(shooting_eng[shooting_eng['Standard_G/SoT'].isna()]['Standard_SoT'].sum())

0.0
0
0
0

In [11]:
#Check passing stats 
#All of the values are NaN becaue they are divided by a 0, so we can impute NaN with 0
for i in ['Total_Cmp%', 'Short_Cmp%', 'Medium_Cmp%', 'Long_Cmp%']:
    print(passing_eng[passing_eng[i].isna()][[i, i.replace('%', '')]])

     Total_Cmp%  Total_Cmp
92          NaN          0
96          NaN          0
99          NaN          0
220         NaN          0
292         NaN          0
344         NaN          0
351         NaN          0
418         NaN          0
527         NaN          0
581         NaN          0
     Short_Cmp%  Short_Cmp
1           NaN          0
92          NaN          0
96          NaN          0
99          NaN          0
219         NaN          0
220         NaN          0
292         NaN          0
344         NaN          0
345         NaN          0
351         NaN          0
365         NaN          0
380         NaN          0
387         NaN          0
418         NaN          0
506         NaN          0
527         NaN          0
574         NaN          0
575         NaN          0
581         NaN          0
     Medium_Cmp%  Medium_Cmp
31           NaN           0
50           NaN           0
88           NaN           0
92           NaN           0
96           NaN           0
99           NaN           0
144          NaN           0
151          NaN           0
157          NaN           0
220          NaN           0
230          NaN           0
261          NaN           0
292          NaN           0
344          NaN           0
345          NaN           0
351          NaN           0
417          NaN           0
418          NaN           0
437          NaN           0
445          NaN           0
484          NaN           0
527          NaN           0
546          NaN           0
581          NaN           0
     Long_Cmp%  Long_Cmp
7          NaN         0
31         NaN         0
39         NaN         0
49         NaN         0
50         NaN         0
65         NaN         0
76         NaN         0
88         NaN         0
92         NaN         0
96         NaN         0
99         NaN         0
120        NaN         0
133        NaN         0
144        NaN         0
151        NaN         0
157        NaN         0
167        NaN         0
174        NaN         0
196        NaN         0
199        NaN         0
217        NaN         0
219        NaN         0
220        NaN         0
230        NaN         0
253        NaN         0
261        NaN         0
287        NaN         0
290        NaN         0
292        NaN         0
306        NaN         0
340        NaN         0
344        NaN         0
351        NaN         0
353        NaN         0
371        NaN         0
372        NaN         0
380        NaN         0
387        NaN         0
390        NaN         0
401        NaN         0
403        NaN         0
405        NaN         0
417        NaN         0
418        NaN         0
427        NaN         0
430        NaN         0
433        NaN         0
437        NaN         0
438        NaN         0
445        NaN         0
465        NaN         0
484        NaN         0
494        NaN         0
496        NaN         0
527        NaN         0
575        NaN         0
581        NaN         0

In [12]:
#Check defense stats
#All of the values are NaN because they are divided by a 0, so we can impute NaN with 0
defense_eng[defense_eng['Challenges_Tkl%'].isna()]['Challenges_Tkl'].sum()

0

In [13]:
#Check possession stats
#All of the values are NaN because they are divided by a 0, so we can impute NaN with 0
print(possession_eng[possession_eng['Take-Ons_Succ%'].isna()]['Take-Ons_Succ'].sum())
print(possession_eng[possession_eng['Take-Ons_Tkld%'].isna()]['Take-Ons_Tkld'].sum())

0
0

In [14]:
#Check miscallenuous stats
#All of the values are NaN because they are divided by a 0, so we can impute NaN with 0
misc_eng[misc_eng['Aerial Duels_Won%'].isna()]['Aerial Duels_Won'].sum()

0

In [15]:
for i in [shooting_eng, passing_eng, gca_eng, defense_eng, possession_eng, misc_eng]:
    print(len(i))

580
580
580
580
580
580

In [16]:
#we also have some players that are actually duplicated in our dataset
#this occurs because there are players who left one of the clubs in EPL and joined another one
shooting_eng[shooting_eng['Player'].duplicated()]

,Player,Nation,Pos,Squad,Age,90s,Standard_Gls,Standard_Sh,Standard_SoT,Standard_SoT%,...,Standard_G/SoT,Standard_Dist,Standard_FK,Standard_PK,Standard_PKatt,Expected_xG,Expected_npxG,Expected_npxG/Sh,Expected_G-xG,Expected_np:G-xG
31,Cameron Archer,ENG,MF,Aston Villa,22,0.1,0,0,0,NaN,...,NaN,NaN,0,0,0,0.0,0.0,NaN,0.0,0.0
76,Armando Broja,ALB,FW,Fulham,21,1.0,0,0,0,NaN,...,NaN,NaN,0,0,0,0.0,0.0,NaN,0.0,0.0
256,Alex Iwobi,NGA,"FW,MF",Fulham,27,24.4,5,51,18,0.353,...,0.28,18.5,0,0,0,5.3,5.3,0.10,-0.3,-0.3
270,Brennan Johnson,WAL,"FW,MF",Nott'ham Forest,22,2.6,0,3,0,0.000,...,NaN,19.7,0,0,0,0.3,0.3,0.11,-0.3,-0.3
347,Neal Maupay,FRA,FW,Everton,26,1.2,0,5,4,0.800,...,0.00,12.5,0,0,0,1.4,1.4,0.29,-1.4,-1.4
351,James Mcatee,ENG,MF,Manchester City,20,0.0,0,0,0,NaN,...,NaN,NaN,0,0,0,0.0,0.0,NaN,0.0,0.0
399,Matheus Nunes,POR,MF,Manchester City,24,7.3,0,9,4,0.444,...,0.00,17.9,0,0,0,0.8,0.8,0.09,-0.8,-0.8
430,Cole Palmer,ENG,MF,Manchester City,21,0.1,0,0,0,NaN,...,NaN,NaN,0,0,0,0.0,0.0,NaN,0.0,0.0
444,Kalvin Phillips,ENG,MF,Manchester City,27,1.0,0,2,0,0.000,...,NaN,21.7,0,0,0,0.1,0.1,0.04,-0.1,-0.1
462,Sergio Reguilón,ESP,DF,Brentford,26,12.4,0,13,1,0.077,...,0.00,18.2,0,0,0,0.8,0.8,0.06,-0.8,-0.8

In [17]:
#Dealing with these duplicates
dfs = [shooting_eng, passing_eng, gca_eng, defense_eng, possession_eng, misc_eng]

for i, df in enumerate(dfs):
    
    #now, these are duplicates, when one player left one of the clubs in EPL and joined another one
    df = df.sort_values(by='90s', ascending=False)

    #instead of dropping these players from our dataset completely, we choose the entry that has the highest 90s
    #meaning he played more matched for that club
    df = df.drop_duplicates(subset='Player', keep='first')

    dfs[i] = df
    
shooting_eng, passing_eng, gca_eng, defense_eng, possession_eng, misc_eng = dfs

In [18]:
for i in [shooting_eng, passing_eng, gca_eng, defense_eng, possession_eng, misc_eng]:
    print(len(i))

570
570
570
570
570
570

In [19]:
#We don't consider goalkeepers because their valuation and statistics are very different from on-field players'

dfs = {'shooting_eng': shooting_eng, 'passing_eng': passing_eng, 'gca_eng': gca_eng, 'defense_eng': defense_eng, 'possession_eng': possession_eng, 'misc_eng': misc_eng}

for name, df in dfs.items():
    dfs[name] = df[df['Pos'] != 'GK']

shooting_eng, passing_eng, gca_eng, defense_eng, possession_eng, misc_eng = dfs.values()

In [20]:
for i in [shooting_eng, passing_eng, gca_eng, defense_eng, possession_eng, misc_eng]:
    print(len(i))

530
530
530
530
530
530

In [21]:
#We're cleaning column Nation
for df in [shooting_eng, passing_eng, gca_eng, defense_eng, possession_eng, misc_eng]:
    df['Nation']=df['Nation'].str.findall(r'[A-Z]+').str.join('')

In [22]:
#Merged statistics - EPL
dfs = [shooting_eng, passing_eng, gca_eng, defense_eng, possession_eng, misc_eng]

merge_cols = ['Player', 'Nation', 'Pos', 'Squad', 'Age', '90s']

merged_df_eng = dfs[0]

for df in dfs[1:]:
    merged_df_eng = pd.merge(merged_df_eng, df, on=merge_cols, how='outer', suffixes=('', '_dup'))

merged_df_eng = merged_df_eng.loc[:, ~merged_df_eng.columns.str.endswith('_dup')]

In [23]:
merged_df_eng

,Player,Nation,Pos,Squad,Age,90s,Standard_Gls,Standard_Sh,Standard_SoT,Standard_SoT%,...,Performance_Crs,Performance_Int,Performance_TklW,Performance_PKwon,Performance_PKcon,Performance_OG,Performance_Recov,Aerial Duels_Won,Aerial Duels_Lost,Aerial Duels_Won%
0,William Saliba,FRA,DF,Arsenal,22,38.0,2,10,3,0.300,...,3,29,26,0,1,0,213,72,49,0.595
1,James Tarkowski,ENG,DF,Everton,30,38.0,1,25,4,0.160,...,6,56,42,0,1,0,186,140,61,0.697
2,Max Kilman,ENG,DF,Wolves,26,38.0,2,14,5,0.357,...,6,39,21,0,1,0,177,86,36,0.705
3,Joachim Andersen,DEN,DF,Crystal Palace,27,37.9,2,21,8,0.381,...,31,41,35,0,0,0,193,89,46,0.659
4,Illia Zabarnyi,UKR,DF,Bournemouth,20,37.0,1,8,2,0.250,...,1,33,32,0,0,0,153,75,60,0.556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525,Lewis Warrington,ENG,FW,Everton,20,0.0,0,0,0,NaN,...,0,0,0,0,0,0,1,0,0,NaN
526,Kaide Gordon,ENG,FW,Liverpool,18,0.0,0,0,0,NaN,...,0,0,0,0,0,0,0,1,0,1.000
527,Daniel Gore,ENG,MF,Manchester Utd,18,0.0,0,0,0,NaN,...,0,1,1,0,0,0,0,0,0,NaN
528,James McConnell,ENG,MF,Liverpool,18,0.0,0,0,0,NaN,...,0,1,0,0,0,0,0,0,0,NaN
529,Thomas Cannon,IRL,FW,Everton,20,0.0,0,0,0,NaN,...,0,0,0,0,0,0,0,0,0,NaN

In [24]:
#Add in an indicator column for the league
merged_df_eng['League']='EPL'

In [25]:
#merged_df_eng.to_csv('/Users/msyzdykova/Desktop/dataset DS project/eng/merged_stats.csv')

# La Liga Statistics

Doing the same preprocessing for La Liga player statistics

In [26]:
#La liga stats
shooting_spa=pd.read_csv('/Users/msyzdykova/Desktop/dataset DS project/spa/la_liga_shooting_stats.csv')
passing_spa=pd.read_csv('/Users/msyzdykova/Desktop/dataset DS project/spa/la_liga_passing_stats.csv')
gca_spa=pd.read_csv('/Users/msyzdykova/Desktop/dataset DS project/spa/la_liga_gca_stats.csv')
defense_spa=pd.read_csv('/Users/msyzdykova/Desktop/dataset DS project/spa/la_liga_defense_stats.csv')
misc_spa=pd.read_csv('/Users/msyzdykova/Desktop/dataset DS project/spa/la_liga_misc_stats.csv')
possession_spa=pd.read_csv('/Users/msyzdykova/Desktop/dataset DS project/spa/la_liga_possession_stats.csv')

In [27]:
#Check for NaN values
for i in [shooting_eng, passing_eng, gca_eng, defense_eng, possession_eng, misc_eng]:
    print(i.isna().sum())

Player                0
Nation                0
Pos                   0
Squad                 0
Age                   0
90s                   0
Standard_Gls          0
Standard_Sh           0
Standard_SoT          0
Standard_SoT%        72
Standard_Sh/90        0
Standard_SoT/90       0
Standard_G/Sh        72
Standard_G/SoT      130
Standard_Dist        72
Standard_FK           0
Standard_PK           0
Standard_PKatt        0
Expected_xG           0
Expected_npxG         0
Expected_npxG/Sh     72
Expected_G-xG         0
Expected_np:G-xG      0
dtype: int64
Player             0
Nation             0
Pos                0
Squad              0
Age                0
90s                0
Total_Cmp          0
Total_Att          0
Total_Cmp%         9
Total_TotDist      0
Total_PrgDist      0
Short_Cmp          0
Short_Att          0
Short_Cmp%        16
Medium_Cmp         0
Medium_Att         0
Medium_Cmp%       21
Long_Cmp           0
Long_Att           0
Long_Cmp%         53
Ast                0
xAG                0
Expected_xA        0
Expected_A-xAG     0
KP                 0
1/3                0
PPA                0
CrsPA              0
PrgP               0
dtype: int64
Player                0
Nation                0
Pos                   0
Squad                 0
Age                   0
90s                   0
SCA_SCA               0
SCA_SCA90             0
SCA Types_PassLive    0
SCA Types_PassDead    0
SCA Types_TO          0
SCA Types_Sh          0
SCA Types_Fld         0
SCA Types_Def         0
GCA_GCA               0
GCA_GCA90             0
GCA Types_PassLive    0
GCA Types_PassDead    0
GCA Types_TO          0
GCA Types_Sh          0
GCA Types_Fld         0
GCA Types_Def         0
dtype: int64
Player              0
Nation              0
Pos                 0
Squad               0
Age                 0
90s                 0
Tackles_Tkl         0
Tackles_TklW        0
Tackles_Def 3rd     0
Tackles_Mid 3rd     0
Tackles_Att 3rd     0
Challenges_Tkl      0
Challenges_Att      0
Challenges_Tkl%    52
Challenges_Lost     0
Blocks_Blocks       0
Blocks_Sh           0
Blocks_Pass         0
Int                 0
Tkl+Int             0
Clr                 0
Err                 0
dtype: int64
Player              0
Nation              0
Pos                 0
Squad               0
Age                 0
90s                 0
Touches_Touches     0
Touches_Def Pen     0
Touches_Def 3rd     0
Touches_Mid 3rd     0
Touches_Att 3rd     0
Touches_Att Pen     0
Touches_Live        0
Take-Ons_Att        0
Take-Ons_Succ       0
Take-Ons_Succ%     59
Take-Ons_Tkld       0
Take-Ons_Tkld%     59
Carries_Carries     0
Carries_TotDist     0
Carries_PrgDist     0
Carries_PrgC        0
Carries_1/3         0
Carries_CPA         0
Carries_Mis         0
Carries_Dis         0
Receiving_Rec       0
Receiving_PrgR      0
dtype: int64
Player                0
Nation                0
Pos                   0
Squad                 0
Age                   0
90s                   0
Performance_CrdY      0
Performance_CrdR      0
Performance_2CrdY     0
Performance_Fls       0
Performance_Fld       0
Performance_Off       0
Performance_Crs       0
Performance_Int       0
Performance_TklW      0
Performance_PKwon     0
Performance_PKcon     0
Performance_OG        0
Performance_Recov     0
Aerial Duels_Won      0
Aerial Duels_Lost     0
Aerial Duels_Won%    39
dtype: int64

In [28]:
#Dropping unnecessary columns
for i in [shooting_spa, passing_spa, gca_spa, defense_spa, possession_spa, misc_spa]:
    i.drop(columns=['Rk', 'Born', 'Matches'], inplace=True)

In [29]:
#Dropping GKs
dfs = {'shooting': shooting_spa, 'passing': passing_spa, 'gca': gca_spa, 'defense': defense_spa, 'possession': possession_spa, 'misc': misc_spa}

for name, df in dfs.items():
    dfs[name] = df[df['Pos'] != 'GK']

shooting_spa, passing_spa, gca_spa, defense_spa, possession_spa, misc_spa = dfs.values()

In [30]:
shooting_spa[shooting_spa['Player'].duplicated()]

,Player,Nation,Pos,Squad,Age,90s,Standard_Gls,Standard_Sh,Standard_SoT,Standard_SoT%,...,Standard_G/SoT,Standard_Dist,Standard_FK,Standard_PK,Standard_PKatt,Expected_xG,Expected_npxG,Expected_npxG/Sh,Expected_G-xG,Expected_np:G-xG
43,Ezequiel Ávila,ARG,FW,Betis,29,3.3,1,9,3,33.3,...,0.33,21.9,0,0,0,0.7,0.7,0.08,+0.3,+0.3
51,Player,N,Pos,Squad,Age,90s,Gls,Sh,SoT,SoT%,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
77,Player,N,Pos,Squad,Age,90s,Gls,Sh,SoT,SoT%,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
103,Player,N,Pos,Squad,Age,90s,Gls,Sh,SoT,SoT%,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
129,Player,N,Pos,Squad,Age,90s,Gls,Sh,SoT,SoT%,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
155,Player,N,Pos,Squad,Age,90s,Gls,Sh,SoT,SoT%,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
163,Abde Ezzalzouli,MAR,FW,Betis,21,9.6,1,33,8,24.2,...,0.13,17.8,0,0,1,3.0,2.2,0.07,-2.0,-1.2
181,Player,N,Pos,Squad,Age,90s,Gls,Sh,SoT,SoT%,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
190,Javi Galán,ESP,DF,Real Sociedad,28,11.9,0,3,1,33.3,...,0.00,20.8,0,0,0,0.1,0.1,0.05,-0.1,-0.1
197,Eric García,ESP,DF,Girona,22,29.3,5,16,6,37.5,...,0.83,9.4,0,0,0,2.8,2.8,0.18,+2.2,+2.2
207,Player,N,Pos,Squad,Age,90s,Gls,Sh,SoT,SoT%,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
233,Player,N,Pos,Squad,Age,90s,Gls,Sh,SoT,SoT%,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
259,Player,N,Pos,Squad,Age,90s,Gls,Sh,SoT,SoT%,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
285,Player,N,Pos,Squad,Age,90s,Gls,Sh,SoT,SoT%,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
311,Player,N,Pos,Squad,Age,90s,Gls,Sh,SoT,SoT%,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
319,Anthony Lozano,HON,FW,Almería,30,8.6,3,23,9,39.1,...,0.33,13.3,0,0,0,3.3,3.3,0.14,-0.3,-0.3
337,Player,N,Pos,Squad,Age,90s,Gls,Sh,SoT,SoT%,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
363,Player,N,Pos,Squad,Age,90s,Gls,Sh,SoT,SoT%,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
389,Player,N,Pos,Squad,Age,90s,Gls,Sh,SoT,SoT%,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
415,Player,N,Pos,Squad,Age,90s,Gls,Sh,SoT,SoT%,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
423,Samu Omorodion,ESP,FW,Granada,19,0.9,1,3,2,66.7,...,0.50,8.6,0,0,0,0.7,0.7,0.23,+0.3,+0.3
441,Player,N,Pos,Squad,Age,90s,Gls,Sh,SoT,SoT%,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
442,Gabriel Paulista,BRA,DF,Valencia,32,15.5,0,7,0,0.0,...,NaN,13.3,0,0,0,0.4,0.4,0.05,-0.4,-0.4
463,Portu,ESP,"MF,FW",Girona,31,13.2,7,21,10,47.6,...,0.70,11.5,0,0,0,3.4,3.4,0.16,+3.6,+3.6
467,Player,N,Pos,Squad,Age,90s,Gls,Sh,SoT,SoT%,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
493,Player,N,Pos,Squad,Age,90s,Gls,Sh,SoT,SoT%,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
519,Player,N,Pos,Squad,Age,90s,Gls,Sh,SoT,SoT%,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
545,Player,N,Pos,Squad,Age,90s,Gls,Sh,SoT,SoT%,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
548,Alex Sola,ESP,"DF,MF",Real Sociedad,24,0.3,0,0,0,NaN,...,NaN,NaN,0,0,0,0.0,0.0,NaN,0.0,0.0
571,Player,N,Pos,Squad,Age,90s,Gls,Sh,SoT,SoT%,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
597,Player,N,Pos,Squad,Age,90s,Gls,Sh,SoT,SoT%,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
609,Nacho Vidal,ESP,DF,Mallorca,28,4.6,0,8,3,37.5,...,0.00,12.3,0,0,0,1.0,1.0,0.13,-1.0,-1.0
612,Jonathan Viera,ESP,MF,Almería,33,10.1,0,12,5,41.7,...,0.00,18.7,1,0,0,1.3,1.3,0.11,-1.3,-1.3
623,Player,N,Pos,Squad,Age,90s,Gls,Sh,SoT,SoT%,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG

In [31]:
dfs = [shooting_spa, passing_spa, gca_spa, defense_spa, possession_spa, misc_spa]

for i, df in enumerate(dfs):
    df = df[df['Player'] != 'Player']

    dfs[i] = df
    
shooting_spa, passing_spa, gca_spa, defense_spa, possession_spa, misc_spa = dfs

In [32]:
for i in [shooting_spa, passing_spa, gca_spa, defense_spa, possession_spa, misc_spa]:
    print(i.dtypes)

Player              object
Nation              object
Pos                 object
Squad               object
Age                 object
90s                 object
Standard_Gls        object
Standard_Sh         object
Standard_SoT        object
Standard_SoT%       object
Standard_Sh/90      object
Standard_SoT/90     object
Standard_G/Sh       object
Standard_G/SoT      object
Standard_Dist       object
Standard_FK         object
Standard_PK         object
Standard_PKatt      object
Expected_xG         object
Expected_npxG       object
Expected_npxG/Sh    object
Expected_G-xG       object
Expected_np:G-xG    object
dtype: object
Player            object
Nation            object
Pos               object
Squad             object
Age               object
90s               object
Total_Cmp         object
Total_Att         object
Total_Cmp%        object
Total_TotDist     object
Total_PrgDist     object
Short_Cmp         object
Short_Att         object
Short_Cmp%        object
Medium_Cmp        object
Medium_Att        object
Medium_Cmp%       object
Long_Cmp          object
Long_Att          object
Long_Cmp%         object
Ast               object
xAG               object
Expected_xA       object
Expected_A-xAG    object
KP                object
1/3               object
PPA               object
CrsPA             object
PrgP              object
dtype: object
Player                object
Nation                object
Pos                   object
Squad                 object
Age                   object
90s                   object
SCA_SCA               object
SCA_SCA90             object
SCA Types_PassLive    object
SCA Types_PassDead    object
SCA Types_TO          object
SCA Types_Sh          object
SCA Types_Fld         object
SCA Types_Def         object
GCA_GCA               object
GCA_GCA90             object
GCA Types_PassLive    object
GCA Types_PassDead    object
GCA Types_TO          object
GCA Types_Sh          object
GCA Types_Fld         object
GCA Types_Def         object
dtype: object
Player             object
Nation             object
Pos                object
Squad              object
Age                object
90s                object
Tackles_Tkl        object
Tackles_TklW       object
Tackles_Def 3rd    object
Tackles_Mid 3rd    object
Tackles_Att 3rd    object
Challenges_Tkl     object
Challenges_Att     object
Challenges_Tkl%    object
Challenges_Lost    object
Blocks_Blocks      object
Blocks_Sh          object
Blocks_Pass        object
Int                object
Tkl+Int            object
Clr                object
Err                object
dtype: object
Player             object
Nation             object
Pos                object
Squad              object
Age                object
90s                object
Touches_Touches    object
Touches_Def Pen    object
Touches_Def 3rd    object
Touches_Mid 3rd    object
Touches_Att 3rd    object
Touches_Att Pen    object
Touches_Live       object
Take-Ons_Att       object
Take-Ons_Succ      object
Take-Ons_Succ%     object
Take-Ons_Tkld      object
Take-Ons_Tkld%     object
Carries_Carries    object
Carries_TotDist    object
Carries_PrgDist    object
Carries_PrgC       object
Carries_1/3        object
Carries_CPA        object
Carries_Mis        object
Carries_Dis        object
Receiving_Rec      object
Receiving_PrgR     object
dtype: object
Player               object
Nation               object
Pos                  object
Squad                object
Age                  object
90s                  object
Performance_CrdY     object
Performance_CrdR     object
Performance_2CrdY    object
Performance_Fls      object
Performance_Fld      object
Performance_Off      object
Performance_Crs      object
Performance_Int      object
Performance_TklW     object
Performance_PKwon    object
Performance_PKcon    object
Performance_OG       object
Performance_Recov    object
Aerial Duels_Won     object
Aerial Duels_Lost    object
Aerial Duels_Won%    object
dtype: object

In [33]:
#Reformatting numerical columns from string to float
dfs = [shooting_spa, passing_spa, gca_spa, defense_spa, possession_spa, misc_spa]

for i, df in enumerate(dfs):

    numeric_cols = df.columns[4:]
    
    for col in numeric_cols:
        if df[col].dtype == 'object':
            if col.endswith('%'):
                df[col] = df[col].str.replace('%', '').astype(float) / 100
            else:
                df[col] = pd.to_numeric(df[col], errors='coerce')

    dfs[i] = df

shooting_spa, passing_spa, gca_spa, defense_spa, possession_spa, misc_spa = dfs

In [34]:
#Check NaN values in shooting stats

#Check distance in shooting stats
#Since the players that have NaN values for Standard_G/SoT, in general, have no other stats (they're all 0), we'll set this column to 0 too
print(shooting_spa[shooting_spa['Standard_Dist'].isna()].iloc[:,6:].sum(axis=1).sum())

#Check Standard_SoT%, Standard_G/Sh, Standard_G/SoT
#These columns have NaN values because the values that they are divided by 0, which in undefined -> so we feel justified to set these values 0
print(shooting_spa[shooting_spa['Standard_SoT%'].isna()]['Standard_SoT'].sum())
print(shooting_spa[shooting_spa['Standard_G/Sh'].isna()]['Standard_Sh'].sum())
print(shooting_spa[shooting_spa['Standard_G/SoT'].isna()]['Standard_SoT'].sum())

0.0
0
0
0

In [35]:
#Check passing stats 
#All of the values are NaN becaue they are divided by a 0, so we can impute NaN with 0
for i in ['Total_Cmp%', 'Short_Cmp%', 'Medium_Cmp%', 'Long_Cmp%']:
    print(passing_spa[passing_spa[i].isna()][[i, i.replace('%', '')]])

     Total_Cmp%  Total_Cmp
136         NaN          0
270         NaN          0
436         NaN          0
474         NaN          0
502         NaN          0
563         NaN          0
     Short_Cmp%  Short_Cmp
136         NaN          0
270         NaN          0
436         NaN          0
474         NaN          0
502         NaN          0
563         NaN          0
599         NaN          0
     Medium_Cmp%  Medium_Cmp
37           NaN           0
136          NaN           0
161          NaN           0
199          NaN           0
270          NaN           0
436          NaN           0
474          NaN           0
502          NaN           0
551          NaN           0
563          NaN           0
567          NaN           0
603          NaN           0
     Long_Cmp%  Long_Cmp
37         NaN         0
50         NaN         0
110        NaN         0
132        NaN         0
136        NaN         0
161        NaN         0
180        NaN         0
199        NaN         0
200        NaN         0
203        NaN         0
218        NaN         0
234        NaN         0
255        NaN         0
266        NaN         0
270        NaN         0
281        NaN         0
305        NaN         0
327        NaN         0
349        NaN         0
365        NaN         0
368        NaN         0
420        NaN         0
425        NaN         0
426        NaN         0
427        NaN         0
436        NaN         0
452        NaN         0
464        NaN         0
474        NaN         0
494        NaN         0
502        NaN         0
514        NaN         0
548        NaN         0
551        NaN         0
563        NaN         0
569        NaN         0
604        NaN         0

In [36]:
#Check defense stats
#All of the values are NaN because they are divided by a 0, so we can impute NaN with 0
defense_spa[defense_spa['Challenges_Tkl%'].isna()]['Challenges_Tkl'].sum()

0

In [37]:
#Check possession stats
#All of the values are NaN because they are divided by a 0, so we can impute NaN with 0
print(possession_spa[possession_spa['Take-Ons_Succ%'].isna()]['Take-Ons_Succ'].sum())
print(possession_spa[possession_spa['Take-Ons_Tkld%'].isna()]['Take-Ons_Tkld'].sum())

0
0

In [38]:
#Check miscallenuous stats
#All of the values are NaN because they are divided by a 0, so we can impute NaN with 0
misc_spa[misc_spa['Aerial Duels_Won%'].isna()]['Aerial Duels_Won'].sum()

0

In [39]:
for i in [shooting_spa, passing_spa, gca_spa, defense_spa, possession_spa, misc_spa]:
    print(len(i))

563
563
563
563
563
563

In [40]:
shooting_spa[shooting_spa['Player'].duplicated(keep=False)]

,Player,Nation,Pos,Squad,Age,90s,Standard_Gls,Standard_Sh,Standard_SoT,Standard_SoT%,...,Standard_G/SoT,Standard_Dist,Standard_FK,Standard_PK,Standard_PKatt,Expected_xG,Expected_npxG,Expected_npxG/Sh,Expected_G-xG,Expected_np:G-xG
42,Ezequiel Ávila,ARG,"FW,MF",Osasuna,29.0,9.6,1,27,6,0.222,...,0.17,21.2,0,0,0,2.0,2.0,0.08,-1.0,-1.0
43,Ezequiel Ávila,ARG,FW,Betis,29.0,3.3,1,9,3,0.333,...,0.33,21.9,0,0,0,0.7,0.7,0.08,0.3,0.3
162,Abde Ezzalzouli,MAR,"FW,MF",Barcelona,21.0,0.8,0,4,1,0.250,...,0.00,19.1,0,0,0,0.2,0.2,0.05,-0.2,-0.2
163,Abde Ezzalzouli,MAR,FW,Betis,21.0,9.6,1,33,8,0.242,...,0.13,17.8,0,0,1,3.0,2.2,0.07,-2.0,-1.2
189,Javi Galán,ESP,DF,Atlético Madrid,28.0,1.0,0,0,0,NaN,...,NaN,NaN,0,0,0,0.0,0.0,NaN,0.0,0.0
190,Javi Galán,ESP,DF,Real Sociedad,28.0,11.9,0,3,1,0.333,...,0.00,20.8,0,0,0,0.1,0.1,0.05,-0.1,-0.1
196,Eric García,ESP,DF,Barcelona,22.0,0.6,0,1,0,0.000,...,NaN,11.0,0,0,0,0.0,0.0,0.05,0.0,0.0
197,Eric García,ESP,DF,Girona,22.0,29.3,5,16,6,0.375,...,0.83,9.4,0,0,0,2.8,2.8,0.18,2.2,2.2
318,Anthony Lozano,HON,"MF,FW",Getafe,30.0,1.0,0,4,0,0.000,...,NaN,15.2,0,0,0,0.2,0.2,0.05,-0.2,-0.2
319,Anthony Lozano,HON,FW,Almería,30.0,8.6,3,23,9,0.391,...,0.33,13.3,0,0,0,3.3,3.3,0.14,-0.3,-0.3
422,Samu Omorodion,ESP,FW,Alavés,19.0,21.3,8,64,24,0.375,...,0.33,13.5,0,0,0,10.8,10.8,0.17,-2.8,-2.8
423,Samu Omorodion,ESP,FW,Granada,19.0,0.9,1,3,2,0.667,...,0.50,8.6,0,0,0,0.7,0.7,0.23,0.3,0.3
440,Gabriel Paulista,BRA,DF,Atlético Madrid,32.0,4.5,0,1,1,1.000,...,0.00,4.7,0,0,0,0.2,0.2,0.19,-0.2,-0.2
442,Gabriel Paulista,BRA,DF,Valencia,32.0,15.5,0,7,0,0.000,...,NaN,13.3,0,0,0,0.4,0.4,0.05,-0.4,-0.4
462,Portu,ESP,FW,Getafe,31.0,1.1,0,1,1,1.000,...,0.00,8.5,0,0,0,0.2,0.2,0.16,-0.2,-0.2
463,Portu,ESP,"MF,FW",Girona,31.0,13.2,7,21,10,0.476,...,0.70,11.5,0,0,0,3.4,3.4,0.16,3.6,3.6
547,Alex Sola,ESP,"FW,MF",Alavés,24.0,14.0,0,28,7,0.250,...,0.00,17.6,2,0,0,1.6,1.6,0.06,-1.6,-1.6
548,Alex Sola,ESP,"DF,MF",Real Sociedad,24.0,0.3,0,0,0,NaN,...,NaN,NaN,0,0,0,0.0,0.0,NaN,0.0,0.0
608,Nacho Vidal,ESP,"DF,FW",Osasuna,28.0,1.1,1,3,1,0.333,...,1.00,12.4,0,0,0,0.3,0.3,0.10,0.7,0.7
609,Nacho Vidal,ESP,DF,Mallorca,28.0,4.6,0,8,3,0.375,...,0.00,12.3,0,0,0,1.0,1.0,0.13,-1.0,-1.0
611,Jonathan Viera,ESP,"MF,FW",Las Palmas,33.0,6.9,2,12,4,0.333,...,0.00,24.0,2,2,2,2.3,0.7,0.06,-0.3,-0.7
612,Jonathan Viera,ESP,MF,Almería,33.0,10.1,0,12,5,0.417,...,0.00,18.7,1,0,0,1.3,1.3,0.11,-1.3,-1.3

In [41]:
#Dropping player duplicates
dfs = [shooting_spa, passing_spa, gca_spa, defense_spa, possession_spa, misc_spa]

for i, df in enumerate(dfs):

    df = df.sort_values(by='90s', ascending=False)

    df = df.drop_duplicates(subset='Player', keep='first')

    dfs[i] = df
    
shooting_spa, passing_spa, gca_spa, defense_spa, possession_spa, misc_spa = dfs

In [42]:
for i in [shooting_spa, passing_spa, gca_spa, defense_spa, possession_spa, misc_spa]:
    print(len(i))

552
552
552
552
552
552

In [43]:
#Merge spa statistics
dfs = [shooting_spa, passing_spa, gca_spa, defense_spa, possession_spa, misc_spa]

merge_cols = ['Player', 'Nation', 'Pos', 'Squad', 'Age', '90s']

merged_df_spa = dfs[0]

for df in dfs[1:]:
    merged_df_spa = pd.merge(merged_df_spa, df, on=merge_cols, how='outer', suffixes=('', '_dup'))

merged_df_spa = merged_df_spa.loc[:, ~merged_df_spa.columns.str.endswith('_dup')]

In [44]:
merged_df_spa

,Player,Nation,Pos,Squad,Age,90s,Standard_Gls,Standard_Sh,Standard_SoT,Standard_SoT%,...,Performance_Crs,Performance_Int,Performance_TklW,Performance_PKwon,Performance_PKcon,Performance_OG,Performance_Recov,Aerial Duels_Won,Aerial Duels_Lost,Aerial Duels_Won%
0,Florian Lejeune,FRA,DF,Rayo Vallecano,32.0,37.0,3,67,21,0.313,...,7,23,25,0,0,1,173,80,49,0.620
1,José Luis García Vayá,ESP,MF,Valencia,24.0,36.7,7,27,5,0.185,...,147,49,53,0,1,0,244,57,42,0.576
2,Nemanja Maksimović,SRB,MF,Getafe,28.0,36.3,4,34,15,0.441,...,5,46,43,0,1,0,140,70,61,0.534
3,Kirian Rodríguez,ESP,MF,Las Palmas,27.0,35.7,6,43,14,0.326,...,26,28,32,0,2,0,231,22,46,0.324
4,Aleix García,ESP,MF,Girona,26.0,35.5,3,39,12,0.308,...,192,36,28,0,0,0,208,17,23,0.425
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,Silvi Clúa,ESP,MF,Girona,18.0,0.0,0,0,0,NaN,...,0,0,0,0,0,0,0,0,0,NaN
548,Bernardo Espinosa,COL,DF,Girona,34.0,0.0,0,0,0,NaN,...,0,0,1,0,0,0,1,1,1,0.500
549,Borja Vázquez,ESP,FW,Cádiz,18.0,0.0,0,0,0,NaN,...,1,0,0,0,0,0,0,0,0,NaN
550,Alberto Perea,ESP,"MF,FW",Granada,32.0,0.0,0,0,0,NaN,...,1,0,0,0,0,0,1,0,0,NaN
551,Álvaro Rodríguez,URU,FW,Real Madrid,19.0,0.0,0,0,0,NaN,...,0,0,0,0,0,0,1,0,0,NaN

In [45]:
merged_df_spa['League']='La Liga'

In [46]:
#merged_df_spa.to_csv('/Users/msyzdykova/Desktop/dataset DS project/spa/merged_stats.csv')

# Combining EPL and La Liga statistics

In [47]:
eng_spa_stats=pd.concat([merged_df_eng, merged_df_spa], axis=0)

In [48]:
eng_spa_stats.reset_index(drop=True, inplace=True)

In [49]:
eng_spa_stats[eng_spa_stats['Player'].duplicated(keep=False)]

,Player,Nation,Pos,Squad,Age,90s,Standard_Gls,Standard_Sh,Standard_SoT,Standard_SoT%,...,Performance_Int,Performance_TklW,Performance_PKwon,Performance_PKcon,Performance_OG,Performance_Recov,Aerial Duels_Won,Aerial Duels_Lost,Aerial Duels_Won%,League
36,Rodri,ESP,MF,Manchester City,27.0,32.6,8,62,22,0.355,...,26,43,1,0,0,235,54,22,0.711,EPL
278,Ben Brereton,CHI,"FW,MF",Sheffield Utd,24.0,12.3,6,34,16,0.471,...,3,4,1,0,0,39,7,23,0.233,EPL
360,Ansu Fati,ESP,"MF,FW",Brighton,20.0,5.8,2,26,11,0.423,...,3,3,0,0,0,22,1,10,0.091,EPL
381,Pablo Fornals,ESP,"MF,FW",West Ham,27.0,4.7,0,7,3,0.429,...,6,6,0,0,0,26,3,6,0.333,EPL
403,Enes Ünal,TUR,"FW,MF",Bournemouth,26.0,3.6,2,23,8,0.348,...,1,4,0,0,0,10,8,11,0.421,EPL
429,Facundo Pellistri,URU,"FW,MF",Manchester Utd,21.0,1.9,0,4,2,0.500,...,1,3,0,0,0,11,6,4,0.600,EPL
439,Hannibal Mejbri,TUN,"MF,FW",Manchester Utd,20.0,1.5,1,1,1,1.000,...,0,3,0,0,0,10,2,4,0.333,EPL
465,Alejo Véliz,ARG,FW,Tottenham,19.0,0.6,1,2,1,0.500,...,0,0,0,0,0,0,1,2,0.333,EPL
508,Bertrand Traoré,BFA,"DF,FW",Aston Villa,27.0,0.1,0,0,0,NaN,...,0,1,0,0,0,2,0,0,NaN,EPL
796,Facundo Pellistri,URU,"MF,FW",Granada,21.0,13.7,2,17,6,0.353,...,4,19,1,0,0,57,9,22,0.290,La Liga
805,Pablo Fornals,ESP,"FW,MF",Betis,27.0,12.8,3,17,5,0.294,...,22,16,0,0,0,72,11,9,0.550,La Liga
821,Rodri,ESP,"FW,MF",Betis,23.0,11.7,0,18,5,0.278,...,8,10,0,0,0,58,0,9,0.000,La Liga
903,Bertrand Traoré,BFA,MF,Villarreal,27.0,6.3,1,20,7,0.350,...,1,4,1,0,0,22,4,3,0.571,La Liga
963,Ben Brereton,CHI,"FW,MF",Villarreal,24.0,3.0,0,5,1,0.200,...,0,2,0,0,0,13,1,2,0.333,La Liga
995,Enes Ünal,TUR,"FW,MF",Getafe,26.0,1.6,0,1,0,0.000,...,0,0,0,0,0,5,3,13,0.188,La Liga
1004,Hannibal Mejbri,TUN,MF,Sevilla,20.0,1.2,0,1,0,0.000,...,0,3,0,0,0,6,0,1,0.000,La Liga
1018,Ansu Fati,ESP,"MF,FW",Barcelona,20.0,0.6,0,7,1,0.143,...,0,0,0,0,0,2,1,1,0.500,La Liga
1025,Alejo Véliz,ARG,FW,Sevilla,19.0,0.4,0,2,2,1.000,...,0,0,0,0,0,0,3,1,0.750,La Liga

In [50]:
eng_spa_stats.iloc[821,0]='Rodri Sanchez'

In [51]:
eng_spa_stats=eng_spa_stats.sort_values(by='90s', ascending=False)
eng_spa_stats=eng_spa_stats.drop_duplicates(subset='Player', keep='first')
eng_spa_stats

,Player,Nation,Pos,Squad,Age,90s,Standard_Gls,Standard_Sh,Standard_SoT,Standard_SoT%,...,Performance_Int,Performance_TklW,Performance_PKwon,Performance_PKcon,Performance_OG,Performance_Recov,Aerial Duels_Won,Aerial Duels_Lost,Aerial Duels_Won%,League
0,William Saliba,FRA,DF,Arsenal,22.0,38.0,2,10,3,0.300,...,29,26,0,1,0,213,72,49,0.595,EPL
2,Max Kilman,ENG,DF,Wolves,26.0,38.0,2,14,5,0.357,...,39,21,0,1,0,177,86,36,0.705,EPL
1,James Tarkowski,ENG,DF,Everton,30.0,38.0,1,25,4,0.160,...,56,42,0,1,0,186,140,61,0.697,EPL
3,Joachim Andersen,DEN,DF,Crystal Palace,27.0,37.9,2,21,8,0.381,...,41,35,0,0,0,193,89,46,0.659,EPL
530,Florian Lejeune,FRA,DF,Rayo Vallecano,32.0,37.0,3,67,21,0.313,...,23,25,0,0,1,173,80,49,0.620,La Liga
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514,Michael Ndiweni,ENG,FW,Newcastle Utd,19.0,0.0,0,0,0,NaN,...,0,0,0,0,0,0,0,0,NaN,EPL
513,Jaden Philogene Bidace,ENG,FW,Aston Villa,21.0,0.0,0,0,0,NaN,...,0,0,0,0,0,1,0,0,NaN,EPL
512,Donny van de Beek,NED,DF,Manchester Utd,26.0,0.0,0,1,0,0.000,...,0,0,0,0,0,0,0,0,NaN,EPL
528,James McConnell,ENG,MF,Liverpool,18.0,0.0,0,0,0,NaN,...,1,0,0,0,0,0,0,0,NaN,EPL
1081,Álvaro Rodríguez,URU,FW,Real Madrid,19.0,0.0,0,0,0,NaN,...,0,0,0,0,0,1,0,0,NaN,La Liga

In [52]:
eng_spa_stats.reset_index(drop=True, inplace=True)

In [53]:
market_values_eng=pd.read_csv('/Users/msyzdykova/Desktop/dataset DS project/values/values_eng.csv')
market_values_ita=pd.read_csv('/Users/msyzdykova/Desktop/dataset DS project/values/values_ita.csv')
market_values_fra=pd.read_csv('/Users/msyzdykova/Desktop/dataset DS project/values/values_fra.csv')
market_values_ger=pd.read_csv('/Users/msyzdykova/Desktop/dataset DS project/values/values_ger.csv')
market_values_spn=pd.read_csv('/Users/msyzdykova/Desktop/dataset DS project/values/values_spn.csv')

In [54]:
for i in [market_values_eng, market_values_ita, market_values_fra, market_values_ger, market_values_spn]:
    print(len(i[i['Name'].duplicated()]))

1
0
0
0
1

In [55]:
#technical mistake
market_values_eng[market_values_eng['Name'].duplicated(keep=False)]

     Unnamed: 0             Name    Position Market Value
474         474  Ricardo Pereira  Right-Back       €8.00m
476         476  Ricardo Pereira  Right-Back       €8.00m

In [56]:
#2 different Juan Cruz's
market_values_spn[market_values_spn['Name'].duplicated(keep=False)]

     Unnamed: 0       Name      Position Market Value
88           88  Juan Cruz  Right Winger       €3.00m
390         390  Juan Cruz     Left-Back       €2.20m

In [57]:
#Juan Cruz in Leganes - 3m, the other in Osasuna - 2.2m
market_values_spn.iloc[88,1]='Juan Cruz_Leganes'
market_values_spn.iloc[390,1]='Juan Cruz_Osasuna'

In [58]:
vals = [market_values_eng, market_values_ita, market_values_fra, market_values_ger, market_values_spn]

stacked_df = pd.concat(vals, axis=0, ignore_index=True)

stacked_df

      Unnamed: 0               Name            Position Market Value
0              0     Erling Haaland      Centre-Forward     €200.00m
1              1        Cole Palmer  Attacking Midfield      €90.00m
2              2          Luis Díaz         Left Winger      €80.00m
3              3        Kai Havertz      Centre-Forward      €75.00m
4              4  Gabriel Magalhães         Centre-Back      €75.00m
...          ...                ...                 ...          ...
2572         497       Sergio Gómez        Right Winger      €10.00m
2573         498     Willy Kambwala         Centre-Back       €5.00m
2574         499       Oli McBurnie      Centre-Forward       €4.50m
2575         500             Adrián          Goalkeeper        €600k
2576         501         Luka Sucic    Central Midfield      €15.00m

[2577 rows x 4 columns]

In [59]:
stacked_df.drop(columns=['Unnamed: 0'], inplace=True)

In [60]:
stacked_df[stacked_df['Name'].duplicated(keep=False)]

                 Name            Position Market Value
273            Danilo  Defensive Midfield      €28.00m
474   Ricardo Pereira          Right-Back       €8.00m
476   Ricardo Pereira          Right-Back       €8.00m
591            Danilo         Centre-Back       €7.00m
783           Vitinha      Centre-Forward      €14.00m
1231          Vitinha    Central Midfield      €55.00m

In [61]:
stacked_df.iloc[273,0]='Danilo_Nttghm'
stacked_df.iloc[591,0]='Danilo_Juventus'

stacked_df.iloc[783,0]='Vitinha_Genoa'
stacked_df.iloc[1231,0]='Vitinha_PSG'

In [62]:
stacked_df[stacked_df['Name'].duplicated(keep=False)]

                Name    Position Market Value
474  Ricardo Pereira  Right-Back       €8.00m
476  Ricardo Pereira  Right-Back       €8.00m

In [63]:
stacked_df.drop_duplicates(subset=['Name'],inplace=True)

In [64]:
stacked_df[stacked_df['Name'].duplicated(keep=False)]

Empty DataFrame
Columns: [Name, Position, Market Value]
Index: []

In [65]:
#stacked_df.to_csv('/Users/msyzdykova/Desktop/dataset DS project/data/values_stacked.csv')

# Merging player statistics with their market values

In [66]:
final_df=eng_spa_stats.merge(stacked_df, left_on='Player', right_on='Name')

In [67]:
final_df

,Player,Nation,Pos,Squad,Age,90s,Standard_Gls,Standard_Sh,Standard_SoT,Standard_SoT%,...,Performance_PKcon,Performance_OG,Performance_Recov,Aerial Duels_Won,Aerial Duels_Lost,Aerial Duels_Won%,League,Name,Position,Market Value
0,William Saliba,FRA,DF,Arsenal,22.0,38.0,2,10,3,0.300,...,1,0,213,72,49,0.595,EPL,William Saliba,Centre-Back,€80.00m
1,James Tarkowski,ENG,DF,Everton,30.0,38.0,1,25,4,0.160,...,1,0,186,140,61,0.697,EPL,James Tarkowski,Centre-Back,€13.00m
2,Joachim Andersen,DEN,DF,Crystal Palace,27.0,37.9,2,21,8,0.381,...,0,0,193,89,46,0.659,EPL,Joachim Andersen,Centre-Back,€35.00m
3,Florian Lejeune,FRA,DF,Rayo Vallecano,32.0,37.0,3,67,21,0.313,...,0,1,173,80,49,0.620,La Liga,Florian Lejeune,Centre-Back,€3.00m
4,Dominic Solanke,ENG,FW,Bournemouth,25.0,36.9,19,106,35,0.330,...,0,0,97,97,135,0.418,EPL,Dominic Solanke,Centre-Forward,€45.00m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,Andrey Santos,BRA,MF,Nott'ham Forest,19.0,0.1,0,2,0,0.000,...,0,0,0,0,0,NaN,EPL,Andrey Santos,Central Midfield,€18.00m
616,César Tárrega,ESP,DF,Valencia,21.0,0.1,0,0,0,NaN,...,0,0,0,0,0,NaN,La Liga,César Tárrega,Centre-Back,€4.00m
617,Mikey Moore,ENG,MF,Tottenham,15.0,0.0,0,0,0,NaN,...,0,0,0,0,0,NaN,EPL,Mikey Moore,Left Winger,€1.00m
618,Donny van de Beek,NED,DF,Manchester Utd,26.0,0.0,0,1,0,0.000,...,0,0,0,0,0,NaN,EPL,Donny van de Beek,Central Midfield,€5.00m
619,Álvaro Rodríguez,URU,FW,Real Madrid,19.0,0.0,0,0,0,NaN,...,0,0,1,0,0,NaN,La Liga,Álvaro Rodríguez,Centre-Forward,€3.50m

In [68]:
#Dropping unnecessary columns because we already have another 2 columns that contain this data
final_df.drop(columns=['Name', 'Position'], inplace=True)

In [69]:
#Cleaning market value column
def convert_market_value(value):
    value = value.replace('€', '')  # Remove the euro symbol
    if 'm' in value:
        return float(value.replace('m', '')) * 1e6  # Convert to millions
    elif 'k' in value:
        return float(value.replace('k', '')) * 1e3  # Convert to thousands
    else:
        return float(value)  # Handle values without suffix

final_df['Market Value'] = final_df['Market Value'].apply(convert_market_value)

In [70]:
final_df

,Player,Nation,Pos,Squad,Age,90s,Standard_Gls,Standard_Sh,Standard_SoT,Standard_SoT%,...,Performance_TklW,Performance_PKwon,Performance_PKcon,Performance_OG,Performance_Recov,Aerial Duels_Won,Aerial Duels_Lost,Aerial Duels_Won%,League,Market Value
0,William Saliba,FRA,DF,Arsenal,22.0,38.0,2,10,3,0.300,...,26,0,1,0,213,72,49,0.595,EPL,80000000.0
1,James Tarkowski,ENG,DF,Everton,30.0,38.0,1,25,4,0.160,...,42,0,1,0,186,140,61,0.697,EPL,13000000.0
2,Joachim Andersen,DEN,DF,Crystal Palace,27.0,37.9,2,21,8,0.381,...,35,0,0,0,193,89,46,0.659,EPL,35000000.0
3,Florian Lejeune,FRA,DF,Rayo Vallecano,32.0,37.0,3,67,21,0.313,...,25,0,0,1,173,80,49,0.620,La Liga,3000000.0
4,Dominic Solanke,ENG,FW,Bournemouth,25.0,36.9,19,106,35,0.330,...,11,1,0,0,97,97,135,0.418,EPL,45000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,Andrey Santos,BRA,MF,Nott'ham Forest,19.0,0.1,0,2,0,0.000,...,0,0,0,0,0,0,0,NaN,EPL,18000000.0
616,César Tárrega,ESP,DF,Valencia,21.0,0.1,0,0,0,NaN,...,0,0,0,0,0,0,0,NaN,La Liga,4000000.0
617,Mikey Moore,ENG,MF,Tottenham,15.0,0.0,0,0,0,NaN,...,0,0,0,0,0,0,0,NaN,EPL,1000000.0
618,Donny van de Beek,NED,DF,Manchester Utd,26.0,0.0,0,1,0,0.000,...,0,0,0,0,0,0,0,NaN,EPL,5000000.0
619,Álvaro Rodríguez,URU,FW,Real Madrid,19.0,0.0,0,0,0,NaN,...,0,0,0,0,1,0,0,NaN,La Liga,3500000.0

In [71]:
#Cleaning up position column because we need to make sure position is a single value, not multiple
#The 2nd position after the comma in some of the entries illustrated a 2nd priority position of the player or rather a position which he sometimes plays in (but it's not his primary position)
#Hence, we remove the 2nd position after the comma
final_df['Pos'] = final_df['Pos'].apply(lambda x: x.split(',')[0])

In [73]:
final_df

,Player,Nation,Pos,Squad,Age,90s,Standard_Gls,Standard_Sh,Standard_SoT,Standard_SoT%,...,Performance_TklW,Performance_PKwon,Performance_PKcon,Performance_OG,Performance_Recov,Aerial Duels_Won,Aerial Duels_Lost,Aerial Duels_Won%,League,Market Value
0,William Saliba,FRA,DF,Arsenal,22.0,38.0,2,10,3,0.300,...,26,0,1,0,213,72,49,0.595,EPL,80000000.0
1,James Tarkowski,ENG,DF,Everton,30.0,38.0,1,25,4,0.160,...,42,0,1,0,186,140,61,0.697,EPL,13000000.0
2,Joachim Andersen,DEN,DF,Crystal Palace,27.0,37.9,2,21,8,0.381,...,35,0,0,0,193,89,46,0.659,EPL,35000000.0
3,Florian Lejeune,FRA,DF,Rayo Vallecano,32.0,37.0,3,67,21,0.313,...,25,0,0,1,173,80,49,0.620,La Liga,3000000.0
4,Dominic Solanke,ENG,FW,Bournemouth,25.0,36.9,19,106,35,0.330,...,11,1,0,0,97,97,135,0.418,EPL,45000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,Andrey Santos,BRA,MF,Nott'ham Forest,19.0,0.1,0,2,0,0.000,...,0,0,0,0,0,0,0,NaN,EPL,18000000.0
616,César Tárrega,ESP,DF,Valencia,21.0,0.1,0,0,0,NaN,...,0,0,0,0,0,0,0,NaN,La Liga,4000000.0
617,Mikey Moore,ENG,MF,Tottenham,15.0,0.0,0,0,0,NaN,...,0,0,0,0,0,0,0,NaN,EPL,1000000.0
618,Donny van de Beek,NED,DF,Manchester Utd,26.0,0.0,0,1,0,0.000,...,0,0,0,0,0,0,0,NaN,EPL,5000000.0
619,Álvaro Rodríguez,URU,FW,Real Madrid,19.0,0.0,0,0,0,NaN,...,0,0,0,0,1,0,0,NaN,La Liga,3500000.0

In [78]:
#Now that we have a combined final dataset we can impute the NaN values with 0
#We are justified to do so because we did check all of the NaN value occurences above and analyzed those situations
final_df.fillna(0, inplace=True)

In [79]:
final_df

,Player,Nation,Pos,Squad,Age,90s,Standard_Gls,Standard_Sh,Standard_SoT,Standard_SoT%,...,Performance_TklW,Performance_PKwon,Performance_PKcon,Performance_OG,Performance_Recov,Aerial Duels_Won,Aerial Duels_Lost,Aerial Duels_Won%,League,Market Value
0,William Saliba,FRA,DF,Arsenal,22.0,38.0,2,10,3,0.300,...,26,0,1,0,213,72,49,0.595,EPL,80000000.0
1,James Tarkowski,ENG,DF,Everton,30.0,38.0,1,25,4,0.160,...,42,0,1,0,186,140,61,0.697,EPL,13000000.0
2,Joachim Andersen,DEN,DF,Crystal Palace,27.0,37.9,2,21,8,0.381,...,35,0,0,0,193,89,46,0.659,EPL,35000000.0
3,Florian Lejeune,FRA,DF,Rayo Vallecano,32.0,37.0,3,67,21,0.313,...,25,0,0,1,173,80,49,0.620,La Liga,3000000.0
4,Dominic Solanke,ENG,FW,Bournemouth,25.0,36.9,19,106,35,0.330,...,11,1,0,0,97,97,135,0.418,EPL,45000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,Andrey Santos,BRA,MF,Nott'ham Forest,19.0,0.1,0,2,0,0.000,...,0,0,0,0,0,0,0,0.000,EPL,18000000.0
616,César Tárrega,ESP,DF,Valencia,21.0,0.1,0,0,0,0.000,...,0,0,0,0,0,0,0,0.000,La Liga,4000000.0
617,Mikey Moore,ENG,MF,Tottenham,15.0,0.0,0,0,0,0.000,...,0,0,0,0,0,0,0,0.000,EPL,1000000.0
618,Donny van de Beek,NED,DF,Manchester Utd,26.0,0.0,0,1,0,0.000,...,0,0,0,0,0,0,0,0.000,EPL,5000000.0
619,Álvaro Rodríguez,URU,FW,Real Madrid,19.0,0.0,0,0,0,0.000,...,0,0,0,0,1,0,0,0.000,La Liga,3500000.0

In [83]:
#final_df.to_csv('/Users/msyzdykova/Desktop/dataset DS project/final scraped df/final_df_new.csv')